github_actions:
- .github/**/*

test:
- test/**/*

knowledge panels:
- lib/model/knowledge_panel.g.dart
- lib/model/knowledge_panel_element.g.dart

product:
- lib/model/product.dart
- lib/model/product.g.dart

robotoff:
- lib/model/robotoff_question.g.dart

pubspec:
- pubspec.yaml

ecoscore:
- lib/model/ecoscore_data.g.dart

personalized search:
- lib/personalized_search/**/*

folksonomy:
- lib/folksonomy.dart
